### ISSUE TITLE
Travis 

### ISSUE THREAD

**Issue by abdullahyldz** [bounswe/bounswe2019group5#101]
I am working on integrating our app with Travis environment. I connected our repository with Travis.CI and added the .travis.yml file .
It is on the Travis Branch. 
I will fill the .travis.yml file  tomorrow , let it test our master.

**Comment by multiminparvo** [comment]
We have a problem about travis integration. Can you  please check again https://github.com/bounswe/bounswe2019group5/pull/100? @abdullahyldz 

By the way, contragulations for #100 issue :))

**Comment by abdullahyldz** [comment]
$ make test
make: *** No rule to make target `test'.  Stop.
The command "make test" exited with 2. 

Same as before, i have this error. I think  it is caused by that i didn't add which tests Travis will build.
But our tests are on different branch 'test'.  Do we need to first merge our tests to master then write our 'test starting scripts'  to .travis.yml?

**Comment by furkan-kadioglu** [comment]
At the beginning of 451, we decided to postpone.

**Comment by ymBila** [comment]
backend is fully integrated to travis ci at the moment
