### ISSUE TITLE
Django vs Node.js for backend

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#106]
We'll discuss under this issue. We also glad to hear @uskudarli and @cihatbaktir  ideas.

**Comment by furkan-kadioglu** [comment]
> [Speed](https://hostpresto.com/blog/should-i-learn-django-or-node-js/): Django was created as a way of helping developers to make applications as quickly as possible. All the way from idea, to production, to release, Django makes development more efficient and cost-effective. This means that it could be an ideal solution if you're worried about deadlines.

**Comment by furkan-kadioglu** [comment]
[Fast development:](https://www.educba.com/django-vs-node-js/)Django makes the development more efficient and cost-effective. Node.js makes development easy but it slows down the process.

**Comment by furkan-kadioglu** [comment]
[Some advantage comparison for django](https://dzone.com/articles/nodejs-vs-djangois-javascript-better-than-python)

- rapid development 
- easy to learn 
- beatiful code


I think that the advantages of Django is more valuable for us in order to actualize our projects.

**Comment by ymBila** [comment]
Here is a way to remove disadvantages of node.js:

We can use a framework like nest.js or sails.js to structure code better. They have auto rest api generation, design patterns like mvc etc. which give node.js all the advantages you mentioned for django. 

On the other hand, node.js has a very important advantage over django: we are more experienced at deployment of node.js. We are going to need extra time for deploying a django app.

**Comment by furkan-kadioglu** [comment]
We decided to Django at Slack
