### ISSUE TITLE
Signup revision 

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#112]
signin becomes signup.
language selectipn will be dropbared.
after prof test rerouting to home page.
frontend branch opening.

**Comment by slmttndrk** [comment]
The frontend branch is created for frontend developers.
SignIn page is converted into the SignUp.
A selection button is added for Native_Language selection.
After finishing the prof exam, the user is redirected to the home page to see his/her overall result.

**Comment by slmttndrk** [comment]
All changes are pushed to the frontend branch and wait for review

**Comment by Melteos** [comment]
it is okay
