### ISSUE TITLE
View for proficiency exam

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#114]
It depends on  #113 due to [test driven development.](https://en.wikipedia.org/wiki/Test-driven_development)

**Comment by furkan-kadioglu** [comment]
- [ ] - Serializer for question model
- [ ] - Custom field for questionOptions

Next steps

**Comment by furkan-kadioglu** [comment]
Api specs update can be needed @ymBila

**Comment by ymBila** [comment]
Creating a proficiency exam is complete, next target is doing evaluation in backend.
