### ISSUE TITLE
Proficiency test result page

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#118]
We need to create the page where the user will land in after completing and submitting the proficiency test. In this page, the user will get to see the result of the test.

**Comment by mstniy** [comment]
A dummy placeholder is ready. You can see it on the branch android_issue117_proficiency_test. The proficiency test activity calls the placeholder results page and passes to it the number of correct vs incorrect answers and the computed proficiency level.

**Comment by muzunpostalci** [comment]
Finalized the page and created pull request #135.
