### ISSUE TITLE
A "bridge" activity for Android

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#139]
As per out milestone goals, we need to have a bridge activity into which the user will land after she logs in or registers. This bridge activity shall let the user jump to the proficiency test of any of the supported languages.

**Comment by haozturk** [comment]
I will work on this bridge activity and report its status through this issue.

**Comment by haozturk** [comment]
I have created the bridge activity. Here is how you can take the language option in your onCreate method @mstniy :

> Bundle langOption = getIntent().getExtras(); 
        if(langOption==null){ 
            return; 
        }
        else {
            String languageChoice = langOption.getString("languageChoice");
            // use this languageChoice for your language option
        }

**Comment by mstniy** [comment]
Issue solved by #154 . Closing it.
