### ISSUE TITLE
Modifying functional user requirements 

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#14]
- [x] @Melteos 

- [x] @ymBila 

- [x] @furkan-kadioglu

**Comment by abdullah-oncu-2015400237** [comment]
Should we only initiate it or do a lot of work on it?

**Comment by ymBila** [comment]
Updated registration-login and course material requirements for user according to the meeting with the customer.

**Comment by slmttndrk** [comment]
Updated Functional Requirements/System Requirements
