### ISSUE TITLE
Main menu activity

### ISSUE THREAD

**Issue by muzunpostalci** [bounswe/bounswe2019group5#142]
We have to create an activity which a user will land after proficiency test result activity or after login.

**Comment by ali-deser-2016400261** [comment]
I think there should be redirections like

- Course Material
- Profile
- Change Language
- Settings
- Log Out

for now

**Comment by ali-deser-2016400261** [comment]
> I think there should be redirections like
> 
> * Course Material
> * Profile
> * Change Language
> * Settings
> * Log Out
> 
> for now

and maybe a Writing redirection in between for future uses?

**Comment by muzunpostalci** [comment]
I have added according redirection into the main menu and created pull request #153.
