### ISSUE TITLE
Connection between Registration page and Bridge Activity

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#143]
Before taking the Proficiency exam, a user shall see a "Select Languages" section. An Intent connection should be maintained on Registration Activity

**Comment by haozturk** [comment]
I will create the Bridge activity as if there is an intent coming from RegistrationPage and I will not create any intent to avoid conflists. Therefore I think you should handle creating the intent in Registraion page. When both activities are finalized we can merge and see the output
