### ISSUE TITLE
Milestone 1: Slides and Scenerios

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#144]
As we all know, we have a demo session on 22.10.2019, we have to prepare some slides introducing our group and project and write two scenarios for Android and Web applications. I guess we can discuss the ideas regarding the milestone on this issue. I think it is more appropriate to assign the preparation of the scenarios Android and Frontend teams. Of course any ideas from the Backend team is welcome.

**Comment by Melteos** [comment]
The slide that we'll complete is shared on whatsapp group. It is a google slides link.
The teams and their responsibilities are:
Backend: about parts of the slide
Frontend: web scenario
Android: android scenario

Frontend part is done
