### ISSUE TITLE
Register Activity: Toast problem

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#149]
There are two problems I observed:

1: When a user is registered successfully, we can make a toast saying that "Account is created successfully"
2: If the user is not created successfully (a blank information or duplicate usernames etc.), we can make a toast saying that "Register is not successful because ..."

Currently, a toast appears in both cases but it is blank

**Comment by uskudarli** [comment]
Is this issue still open? seems like a long time for an "in progress" task,

**Comment by ali-deser-2016400261** [comment]
Forgot to track this issue, due to a minor bug which I was dealing with the other issue. Done
