### ISSUE TITLE
Research about tracking for completed tasks

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#15]
* Monthly/Weekly workflow diagram can be useful for tracking.
* draw.io can be considered as a tool.

**Comment by multiminparvo** [comment]
We should create a workflow like that:
![image](https://user-images.githubusercontent.com/15251670/53287704-fcf14780-3790-11e9-95ef-031551e31d20.png)
Of course in our case it would be more simple than this one.

Workflow can be changed according to task type. For instance if we work on documentation of the requirements the the task type can be documentation. The workflow should like: pool/backlog- document in progress-document done- review- review fix- done
If we work on some research task, it should be like 
pool/backlog- research in progress- research done-review-review done

**The description of the states:**
Pool/backlog state is that we decide to what is the description task, how much effort will it take, what is the description type etc. Actually we are doing this step at our meetings. The name of the state can be pool or backlog in our project.

We can use 'in progress step' for tracking when the developer starts her/his task and how much time does it take to code/search/document it.

We also take  review step into consideration.One or two code reviwer shoul read the developer's code and mentioned what part that s/he should fix in her/his code. Actually again one more question: **Will we apply a code review standards in our project?**  It is also very important topic before starting the development.

**The another important part of the workflow is testing or in other words QA.** Will we apply this step in our project? I mean should we add a step for test like normal user. Developer may not see what s/he messes up while coding.  If we have a QA step, it would be very professional but it may take some time of course.

**And another important thing for workflow is that  a student must have only one task at the inprogress state.** If s/he finishes a task, s/he can proceed another one ofcourse but not two of them at the same time.It is very crucial for in progress state.

**Comment by multiminparvo** [comment]
I think we should write a workflow manifest ant put it our wiki page
