### ISSUE TITLE
Android: Title Bar

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#155]
I think the title bar appearing at the top of our activities does not look good. (says "languageLearning"). If everyone agrees we can remove it from our activities. Here is how you can remove it in your onCreate methods:

> //remove title bar
        try
        {
            this.getSupportActionBar().hide();
        }
        catch (NullPointerException e){}
        setContentView(R.layout.[layout name]);

**Comment by furkan-kadioglu** [comment]
What is the progress for 27 days??? If completed then close!

**Comment by haozturk** [comment]
Please watch your tone! Because it has a low priority, obviously this issue has starved in our schedule. Of course this is a mistake of ours, we should have tracked it anyway. But I think you could have done a friendly warning rather than aggressive one.

**Comment by haozturk** [comment]
Seems like everyone removed title bars in their activities, so closing.
