### ISSUE TITLE
Previous error message stays when trying to login/signup again

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#156]
In index.js of login page at line 101                

{this.props.authentication.message!=null &&
                  (
                    <div>
                      <label style={{color: 'red'}}>{this.props.authentication.message}</label>
                    </div>
                  )
                }

error message in our state stays, maybe it should be deleted after..

**Comment by abdullah-oncu-2015400237** [comment]
The problem is related to State management in our project. A general solution for the whole of our project will be decided after milestone.

**Comment by abdullah-oncu-2015400237** [comment]
I have added clear functions for states. Some when a page is loaded, now, related states are cleared. We don't want to see past data, so we can delete them safely.
