### ISSUE TITLE
Modifying the non-functional requirements

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2019group5#16]
If you want to modify the non-functional requirements, please add your name below and make your self one of the asignee

- [x]  @multiminparvo 
- [x]  @hasan-ozturk-2017400258 
- [x]  @abdullahyldz

**Comment by multiminparvo** [comment]
We can use this links as a referenced for writing non-functional requirements

https://github.com/bounswe/bounswe2018group3/wiki/Project-Requirements/17b180ace99efb1871ddf1a56686752a52f68d84

https://github.com/bounswe/bounswe2016group6/wiki/Requirements

**Comment by abdullahyldz** [comment]
I am working on Performance and Response time and Reliability.

**Comment by multiminparvo** [comment]
I will work on these parts
- Availability and Accessibility
- Security
- Portability

**Comment by hasan-ozturk-2017400258** [comment]
I am working on Annotations. I also review others' sections and updating glossary.
