### ISSUE TITLE
Creating profile page

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#176]
I will implement the profile page to our web application It will look similar to this draft:
![WhatsApp Image 2019-10-27 at 21 37 27](https://user-images.githubusercontent.com/41024883/67639557-3e2e8e00-f902-11e9-82cf-144a5fa9c674.jpeg)

**Comment by Melteos** [comment]
things left to do: 
ratings&comments should also be seen on profile page
attended_languages is not set(should be set when on page lang-select)
general styling
adding settings part?

**Comment by furkan-kadioglu** [comment]
Can you set milestone for requirements as frontend? As backend and mobile, we cannot track frontend progress due to lack of issues. @Melteos @slmttndrk @abdullah-oncu-2015400237 @ymBila

**Comment by Melteos** [comment]
-overall rating -set this in userInfo
-statistics, with test-result
-styling!
-informations about funcitonalities to the user for better understanding
