### ISSUE TITLE
Modifying functional system requirements

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#19]
- [x]  @abdullah-oncu-2015400237 

- [x]  @muzunpostalci 

- [x] @ali-deser-2016400261 

- [x] @slmttndrk

**Comment by ali-deser-2016400261** [comment]
Made some improvements, yet still in progress

**Comment by muzunpostalci** [comment]
Added items 1.2.9 and 1.2.10
