### ISSUE TITLE
Connect the Android profile page to the backend

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#193]

**Comment by haozturk** [comment]
@mstniy I have tried to connect the profile page to the backend, but for some reason it fails. When I put breakpoints both inside of onResponse and onErrorResponse, none of them is executed. Probably I make a simple mistake. Can you please check this out? Here is link to the API call: https://github.com/bounswe/bounswe2019group5/blob/android_issue193_profileConn/languageLearning/app/src/main/java/com/example/languageLearning/ProfilePage.java#L74

**Comment by furkan-kadioglu** [comment]
Latest version of apk which is sent to me in today, profile page is connected. What is the status of this issue? Please update

**Comment by haozturk** [comment]
There is still a bug in this connection, can you please share the apk that you are talking about with me?

**Comment by haozturk** [comment]
Problem is solved [here](https://github.com/bounswe/bounswe2019group5/pull/246) thanks to @mstniy. Please check out the new version @furkan-kadioglu
