### ISSUE TITLE
Create a chat history screen for Android

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#196]

**Comment by furkan-kadioglu** [comment]
Frontend designed chat screen 8 days ago.Can we talk about any progress for mobile?

**Comment by haozturk** [comment]
Backend connection is established. At this point rendering the response and showing to the screen is left to do.

**Comment by haozturk** [comment]
The development is done for this functionality. See this [PR](https://github.com/bounswe/bounswe2019group5/pull/291)
