### ISSUE TITLE
Create an exercise activity for Android

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#197]
It needs to display questions and let the user answer them.
It needs to be usable from both the search result screen and the random exercise button on the main screen.

**Comment by mstniy** [comment]
Adding a checklist containing stuff to do:

- [ ] Create the actual exercise activity
- [ ] Let the user access this exercise activity from the search result screen
- [ ] Let the user access this exercise activity using the "get random exercise" button on the main screen
- [ ] Create an activity to show to the user the correct answers

**Comment by furkan-kadioglu** [comment]
If this issue depends on #195 and #198 then please update label to blocked. Also #198 is labeled by @muzunpostalci 3 days ago without reviewer
