### ISSUE TITLE
Add a "random exercise" button to the main screen

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#198]
It needs to contact the backend and ask for a new, random exercise and start the exercise activity with the exercise it receives.

**Comment by ali-deser-2016400261** [comment]
I think this @muzunpostalci was assigned to this issue. I am correcting

**Comment by muzunpostalci** [comment]
Done and created pull request.

**Comment by furkan-kadioglu** [comment]
If it is completed then please update
