### ISSUE TITLE
Updating requirements according to detailed feedbacks

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#20]
### Yorumlarda Herkes Yapacağı İşin Numarasını Belirtsin.
**Communication Plan Feedback**
1. - [x] Just as a minor feedback, you may add Piazza for communicating with the customers when necessary. 

**Requirements Feedbacks**

2. - [x] It would be better to add some terminologies to glossary, such as "proficiency exam", "tag" or "content". 
3. - [x] 1.1.1.2.1 requires more information about the necessary personal info
4. - [x] 1.1.1.3.1 what is the scope of the limited content?
5. - [x] It would be better to add specific languages that will be available within the system. Which languages will be supported? You don't need to add lots of languages, just 3-4 languages will be enough. 
6. - [x] You may need to use "shall be able to" instead of "shall" in some of the requirements that define some capabilities that user can do within the system. 
7. - [x] Levels may need more discussion. What is the higher or lower level?
8. - [x] In my opinion, do not differentiate "experts" and "users" while writing the requirements. For example, in 1.1.3.5, any user can reject if there is any assigned writing document. The expertise is defined only through the profile and experiences of a user. 
9. - [x] Admin users should be defined. 
10. - [x] Exercising should be defined in detail. For example, assume that there are 20 multiple choice questions provided by a certain material. Shall a user see the correct answer as the choice is selected, or a report for all questions is generated once 20 questions are completed? Think about these conditions in detail.
11. - [x] 1.1.6 what can be the other details about tracking/monitoring? Only the accomplished tasks?
12. - [x] 1.2.1.1 the content will be provided by the users. Yes, the content is available on the system but the system itself does not automatically provide something or behave according to the coding with regards to the contents. 
13. - [x] 1.2.1.2 is not necessary in requirements, it is an algorithmic decision. 
14. - [x] 1.2.2 requires rephrase. A better option may be "the system shall provide a mechanism for searching a content semantically". 
15. - [x] 1.2.4.1 actually this functionality is provided in user requirements (1.1.7). Extra requirement for providing an interface is not necessary.
16. - [x] 1.2.4.2 delete "also" :) 
17. - [x] Similarly, 1.2.7.1 is also related to user requirements about "user shall be able to add/suggest new materials". These mechanisms are provided by the system, but they are the use cases that a user can interact with. If a user can do something within the system, of course there should be an interface provided by the system. But these kind of requirements should be defined only as user requirements. However, for example searching, user shall be able to search a content within the system. The mechanism provided by the application is not the searching one, but searching "semantically" at the background. Semantic is not something that user can manipulate. It would be better to distinguish them. 
18. - [x] 2.1.1 better to write Android and browser versions as compatibility issues. 
19. - [x] In non-functional requirements, the protocols that should be followed needs to be specified.

**Comment by multiminparvo** [comment]
18

**Comment by Melteos** [comment]
1, 3, 6

**Comment by abdullahyldz** [comment]
5-7-8-9

**Comment by abdullah-oncu-2015400237** [comment]
12-17 done

**Comment by Melteos** [comment]
I've done 6 but someone should also review that in case i missed some of them.

**Comment by multiminparvo** [comment]
18 done. 

I think it would be better  if we write "1.1.3.1. Users shall be able to upload essays for writing exercises" instead of the current one. What do you think @Melteos ?

**Comment by Melteos** [comment]
@multiminparvo it had been discussed in the ps and chat said it makes sense to leave it as "shall" that's why i didn't change it.

**Comment by hasan-ozturk-2017400258** [comment]
Nonfunctional requirements are updated according to the feedback

**Comment by ymBila** [comment]
Added admin user requirements

**Comment by ali-deser-2016400261** [comment]
Completely D O N E
