### ISSUE TITLE
New proficiency test questions

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#206]
We don't seem to have any questions on the proficiency test of any language. We need to add some

**Comment by furkan-kadioglu** [comment]
Not only proficiency exam, but also exercise and other contents are needed to check whether functionalities work properly or not. Therefore, we should specify what kind of contents are needed at the initialization of dB in JSON format. And then we can add them automatically at the beginning. 
If we decide to initiate this kind of json file, which kind of content should be first?

**Comment by furkan-kadioglu** [comment]
Specified json files in `initialization_database` directory with respect to given format
**user.json**
```json
{
  "users": [
    {
      "name": "Ada",
      "surname": "Lovelace",
      "email": "adaLovelace@emal.com",
      "username": "ada",
      "password": "isa21-ad",
      "native_language": "english"
    }
  ]
}
```

**exercise.json**
```json
{
  "exercises": [
    {
      "language": "english",
      "type": "vocabulary",
      "level": "A1",
      "tags": [
        "basketball",
        "football"
      ],
      "keywords": [
        "hard"
      ],
      "questions": [
        {
          "text": "question text",
          "answer": "the answer of question",
          "question_options": [
            {
              "text": "first option"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by furkan-kadioglu** [comment]
Alternatively, you can wait until endpoint provides the suggestion of materials.

**Comment by mstniy** [comment]
Where are these files? In which branch?
Can we, the mortal non-backend people, contribute to them?

**Comment by furkan-kadioglu** [comment]
Db cannot be destroyed anymore. You can use Django admin panel to add them.

**Comment by ali-deser-2016400261** [comment]
I added some before, and I will add more soon

**Comment by mstniy** [comment]
We now have prof exams in all three languages. Closing this issue.
