### ISSUE TITLE
Mockups-Scenario 1

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#21]
**Web part of the Scenarios**
Scenario 1 discussed in meeting will be detally discussed on a subgroup meeting Friday between 11-13
Mockups related to it will be created

**Comment by ali-deser-2016400261** [comment]
90-95% of work done, last reviews & corrections will be made

**Comment by slmttndrk** [comment]
Some changings about mockup images and scenario are made.  Last reviews & corrections will be made.

**Comment by abdullah-oncu-2015400237** [comment]
I've reviewed, it seems there is not any big problem.
