### ISSUE TITLE
Add the option to upload essays

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#222]
As part of the project requirements, we need to allow users to upload essays. We need to create an activity where the user can choose to upload a file or write an essay within the app, and another one where he can select among the recommended reviewers. Once this is complete, the endpoint should be notified of this new essay.

**Comment by furkan-kadioglu** [comment]
if it is completed then you should project chart and labels @mstniy

**Comment by mstniy** [comment]
PR #230 solved this.
