### ISSUE TITLE
Get /essay/ does not return the author of the essays

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#224]
The endpoint returns both essays authored by the current user and essays for which the current user is the reviewer. For the latter case, the user probably also needs to know the author of the essay. The endpoint does not return this information.

**Comment by furkan-kadioglu** [comment]
If you want assign me to backend related issues then you should add backend labels.

**Comment by furkan-kadioglu** [comment]
Author field returns in requests for essay endpoints. Deployed

**Comment by mstniy** [comment]
The issue is solved, then.
