### ISSUE TITLE
Absence of current selected language and bridge activity routing issue

### ISSUE THREAD

**Issue by muzunpostalci** [bounswe/bounswe2019group5#225]
Currently we don't hold the current language in our program. We may hold this value in a global variable. Any other suggestions are welcome.

Other language issue is current bridgeActivity only routes to ProfExamActivity and gives a toast error if the proficiency exam of that language has been taken. We may use this bridgeActivity also to change current language and route back to the mainMenuActivity if the proficiency exam has been taken.

**Comment by muzunpostalci** [comment]
Created a global variable to hold current language [here](https://github.com/bounswe/bounswe2019group5/commit/2c26fae59421fc3bfd27ee19f9d98c60a2565343) for now to keep implementing. I have set its default value to "english", in another commit, to prevent it from being empty.

**Comment by muzunpostalci** [comment]
Pull request #226 includes above commits.

**Comment by furkan-kadioglu** [comment]
> Pull request #226 includes above commits.

I closed this issue because pr is reviewed and merged

**Comment by muzunpostalci** [comment]
Thank you for your volunteering @furkan-kadioglu but this is not completed yet! We can discuss and close it if necessary.
Above pull request only solves part of the problem. BridgeActivity does not changes the language fıeld yet.
I am reopening it.

**Comment by mstniy** [comment]
It does not seem to check if the proficiency exam has already been solved either.
Maybe create a checklist consisting of stuff that remains to be fixed?

**Comment by mstniy** [comment]
I'll be working on this

**Comment by mstniy** [comment]
PR #281 fixed this.
