### ISSUE TITLE
Create expert recommendation page

### ISSUE THREAD

**Issue by ymBila** [bounswe/bounswe2019group5#235]
Create expert recommendation page for writing exercises. Endpoint will have url /recommendation @furkan-kadioglu

**Comment by furkan-kadioglu** [comment]
> Create expert recommendation page for writing exercises. Endpoint will have url /recommendation @furkan-kadioglu

Endpoint is deployed 15 Nov 2019 - 17.54

**Comment by ymBila** [comment]
development done, pr opened at: https://github.com/bounswe/bounswe2019group5/pull/240

**Comment by slmttndrk** [comment]
"Recommendation Page" is now available without any problems.
