### ISSUE TITLE
Mockup-Scenario 2

### ISSUE THREAD

**Issue by ymBila** [bounswe/bounswe2019group5#25]
Mockup tools will be searched. Scenario 2 will be discussed. Meeting will be between 15:00-17:00 Thursday, 28.02.2019. @cmpe lounge

**Comment by ymBila** [comment]
Balsamiq is chosen as our mock up tool. The details of scenario 2 are decided. A persona is decided.

**Comment by ymBila** [comment]
5 pages are finished, needs review from rest of the team.

**Comment by Melteos** [comment]
Scenario2 is added to mockups page by me. Only user story left to edit

**Comment by abdullahyldz** [comment]
I added user stories for Aliye Çiçekçi to User Stories section.

**Comment by ali-deser-2016400261** [comment]
Well done, I think it's okay
