### ISSUE TITLE
Removing listening question body limit

### ISSUE THREAD

**Issue by slmttndrk** [bounswe/bounswe2019group5#250]
While I am adding listening questions from admin panel, I have encountered string character limit as 1001 chars. Since we are adding base64 converted version of any audio files, their string lengths are much longer than 1001 chars. In our database, we should be able to keep longer strings in order to fetch the audio files. So, I think the backend team should remove this limit or suggest another solution.

**Comment by furkan-kadioglu** [comment]
character limit is implied by Django, however I have changed to 10000000. Please give me feedback. Is it enough for you?

**Comment by slmttndrk** [comment]
I converted a three minute long audio file into base64 format and its character length was 2212208. So, I seems this new limit is adequate for our purpose. But again when I tried to add a listening question, even smaller than previous string such as 200000 character-long string, the panel does not works properly. I think it stems from timeout because uploading these long string maybe diffucult for the system. Maybe my machine is not working properly. Can you try to add a 200000 character-long string into question body. If you also see this problem, then it seems adding it from panel is not suitable for us.

**Comment by furkan-kadioglu** [comment]
What is the time limitation for listening questions? I think that 3 minutes is too much for this exercise. Maybe we can discuss about how much time Memrise and Duolingo handle?

**Comment by slmttndrk** [comment]
At first, I think you did not understand the string lengths. "2212208" was for measuring the maximum limit such that a three-minute-long-audio and "200000" was for the minimum length audio that is two-second-long-audio. So, I mean even if we try to use smaller sized audios, it is very long string to add into the panel. 

Secondly, as you said, changing the field did not work properly.

Finally, I also agree with that listening exercise should be limited. As I said, the problem stems from adding this much long string even for a smaller audio file. And, I inspected the "Memrise" and saw that they use just urls of the audio files that they store some servers. My opinion is that, we also should just give audio url instead of base64 string. 

In addition to that, I think we should split listening exercise from other exercises like writing exercise and construct a different structure where we could upload urls of audio files and add another parameter that will show the question for that specific listening exercise. Since all audio files do not contain question part in their files. What do you think about? @furkan-kadioglu @mstniy

**Comment by furkan-kadioglu** [comment]
I got it problem. I have written alternative way to base64. We will talk about alternatives in meeting. #255 is ready alternative for meeting.

**Comment by furkan-kadioglu** [comment]
Merged #255
