### ISSUE TITLE
TextEssayDetailActivity has issues regarding essays with images

### ISSUE THREAD

**Issue by muzunpostalci** [bounswe/bounswe2019group5#251]
TextEssayDetailActivity can not show an essay that is uploaded as image. I have tracked the issue to the point; when Essay object has an id from which essay that its URI points to a png file, app crashes. When id is from an txt essay and URI still points to the png file app does not crash but prints image as characters.

From what I have understood TextEssayDetailActivity can't show the details of image essays.

**Comment by mstniy** [comment]
TextEssayDetailActivity is for text essays, ImageEssayDetailActivity is for image essays. This behaviour is expected.
