### ISSUE TITLE
Android app new material suggestion

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#258]
The user should be able to suggest new material.

**Comment by muzunpostalci** [comment]
I will implement this feature.

**Comment by muzunpostalci** [comment]
I have implemented this feature and created pull request #285.

**Comment by mstniy** [comment]
Suggesting listening exercises is not possible as of now. The other execise types can be suggested.

**Comment by mstniy** [comment]
We can re-use the code that uploads image essays to upload audio files.

**Comment by muzunpostalci** [comment]
I have implemented listening exercise suggestion feature and opened pull request #335.

**Comment by mstniy** [comment]
PR #335 solved this
