### ISSUE TITLE
Android profile page see comments and ratings

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#265]
The user should be able to see what other users have voted/commented about him in his profile page. The current "View Comments" button in the profile page does not work.

**Comment by haozturk** [comment]
Thanks for raising an issue for this. It seems like there is no endpoint where a user can post a comment and rate about another user yet. But I can write this functionality as if it exists.

**Comment by mstniy** [comment]
Pull requests #261 and #278 fixed this.
