### ISSUE TITLE
Need for an endpoint where a user can post a comment and a rate for another user

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#266]
As far as I see in the [API documentation](http://35.158.176.194/docs/) there is no endpoint where a user can post a comment or a rate for another user. That's why we cannot show these information in the profile page of a user in our Android app.

These functionalities relate to requirement 1.1.7.2 and 1.1.7.3 in our [requirements](https://docs.google.com/document/d/1eE29ZevkNggZeJy2ZUJTmZCyr-MDINBqh9HDZt3IzOQ/edit#heading=h.n8exg8x5hc1c)

I hope, I do not miss anything.

Many thanks,
Hasan

**Comment by furkan-kadioglu** [comment]
There has already exist
