### ISSUE TITLE
Seeing taken proftest or other exercises again

### ISSUE THREAD

**Issue by slmttndrk** [bounswe/bounswe2019group5#271]
I think there is a problem in backend about seeing taken proftest or other exercises again. It should not return client side any taken tests but all of them are returned. As a consequence, re-trying to complete the test/exercise again, it gives error such as 500 (Internal Server Error). Can you control this functionality @furkan-kadioglu @nevzatersoy ?

**Comment by furkan-kadioglu** [comment]
Fixed
