### ISSUE TITLE
Questions for customer meeting 19.03.2019

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#28]
Prepare questions for customer meetings

**Comment by furkan-kadioglu** [comment]
* Guest user exact definition

**Comment by hasan-ozturk-2017400258** [comment]
Lets say there are multiple include options for a specific node. It only requires at least one include. How should we approach this problem?

**Comment by furkan-kadioglu** [comment]
Different branch connection dilemma @class diagram

**Comment by furkan-kadioglu** [comment]
> Lets say there are multiple include options for a specific node. It only requires at least one include. How should we approach this problem?

extend yeterli olur denildi

**Comment by furkan-kadioglu** [comment]
> * Guest user exact definition

egzersizlerden birer tane görebilecek.

**Comment by Melteos** [comment]
In the chatting, should a user be able to send chat request for different languages to the same person?
What if they already have an active chat in one language?

**Comment by Melteos** [comment]
Suggestexercise
Addexercise 
How should we handle this in clasd diagram

**Comment by Melteos** [comment]
Amazon cognito usage.

**Comment by furkan-kadioglu** [comment]
* Essay Circle
