### ISSUE TITLE
Android choose language at login

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#280]
The app currently assumes English as the language. The user should be able to choose which languages he wants to practice after logging in.

**Comment by ali-deser-2016400261** [comment]
For an approach:
We already have Change Language section, maybe we can set this view as mandatory to give the user an option.
I can implement this

**Comment by mstniy** [comment]
Is there any progress on this?

**Comment by ali-deser-2016400261** [comment]
https://github.com/bounswe/bounswe2019group5/pull/373 Related PR
