### ISSUE TITLE
Profile page comment count

### ISSUE THREAD

**Issue by muzunpostalci** [bounswe/bounswe2019group5#286]
In profile page, showing comment count beside average rate would be much more informative as there is a difference between 2 comments and 50 comments.

Also we can limit the average rate to 2 decimal places after point for better view.

![Ek Açıklama 2019-11-22 015125](https://user-images.githubusercontent.com/32355922/69383463-be120300-0cca-11ea-98e8-9051cd500458.png)

**Comment by muzunpostalci** [comment]
I am assigning @mstniy, as you implemented commenting and rating in profile page.

**Comment by ali-deser-2016400261** [comment]
Yes and agreed. We had a meeting with customer Cihat, and he also told us that there is a distinction between getting 5/5 from only 1 user and getting 4.8/5 from let's say 50 users.
And he recommended us to have a label like <Over # Users> next to the Average.

**Comment by mstniy** [comment]
Is it fine if we show the exact number of users who voted for each rating?
Like 3 users voted 1 star, 5 users voted 5 stars etc.

**Comment by ali-deser-2016400261** [comment]
I think it is also fine if we have enough space for it
![image](https://user-images.githubusercontent.com/32370455/69460163-7ea7ed00-0d84-11ea-886f-9ce41e96ee5e.png)
Something like that can be implemented.

Or just the drag attention something like that : **3.6/5 (Over 35 Ratings)**

**Comment by mstniy** [comment]
Ok, I'll be working on it

**Comment by mstniy** [comment]
PR #289 fixed this
