### ISSUE TITLE
Registration does not correctly saves native language

### ISSUE THREAD

**Issue by muzunpostalci** [bounswe/bounswe2019group5#287]
While I am implementing user search, issued #282, I have seen that some users native language is "Turkish" while others "turkish". When I looked at the admin panel I saw that users with Upper cased native_language fields does not have a valid Native Language.

![image](https://user-images.githubusercontent.com/32355922/69426984-8abd8b80-0d3f-11ea-8de9-e5049bcd3704.png)

![image](https://user-images.githubusercontent.com/32355922/69426926-6c579000-0d3f-11ea-947f-24885be50c96.png)

Registering via Android does not correctly sends native_language field to backend. This field must be all lower case while RegisterActivity sends backend first letter as upper case. Backend accepts this request so it couldn't be detected.
If we correct the issue in RegisterActivity there is no need for backend to change the endpoint. But it may be good for solidarity of backend to reject this type of request.

**Comment by muzunpostalci** [comment]
I will solve the issue in RegisterActivity.

**Comment by muzunpostalci** [comment]
I am tagging @furkan-kadioglu to get attention. You may want to reject said requests and also assign someone else from backend team if you want.

**Comment by ali-deser-2016400261** [comment]
Good point, merged

**Comment by furkan-kadioglu** [comment]
> I am tagging @furkan-kadioglu to get attention. You may want to reject said requests and also assign someone else from backend team if you want.

I have deployed backend which rejects invalid requests.
