### ISSUE TITLE
Customizing the issues

### ISSUE THREAD

**Issue by hasan-ozturk-2017400258** [bounswe/bounswe2019group5#3]
Customize the “issues” by specializing them.  For example,  decide on the types and colors of tags.

**Comment by furkan-kadioglu** [comment]
Automatization was completed in order to customize labels. For more details, please see [Relequestual Sensible Github Labels](https://github.com/Relequestual/sensible-github-labels) and [git-label](https://github.com/jasonbellamy/git-label)

**Comment by abdullah-oncu-2015400237** [comment]
Done.
