### ISSUE TITLE
Proficiency Test Mechanism & Attended Language-Level Relationship is not sufficient

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#301]
Currently, we add the proficiency exercise and it's questions to the system for a specific language(It's level must be A1 otherwise we cannot display prof. questions).
- And as far as I test and observe, the best that a user can achieve is A2. Correct me if I'm wrong but that was what I see after a couple of trials.
Which means that users with Degree B1 B2 C1 C2 cannot exist in the system.
- I think that the logic of the proficiency should be improved and a user with higher levels should also exist in the system. (At least at the beginning of the system & we can implement level improvements and end section prof. tests to implove levels later)
- Additionaly, from the admin panel I see one Level section even if the user attends 2 or more language. Is that mean a user with multiple level relationships cannot exist? For example : A User with B1 Level with English and A2 Level with German should also exist in the system

**Comment by furkan-kadioglu** [comment]
deployed
