### ISSUE TITLE
Annotation colors

### ISSUE THREAD

**Issue by haozturk** [bounswe/bounswe2019group5#302]
According to the milestone 2 feedback:

Annotation colors should not be random. If there are multiple colors, each color should have a meaning. For instance, one color could represent typos, some other color can represent a suggestion etc.

**Comment by mstniy** [comment]
Do we really need that? It sounds overly complicated and confusing. The user  can just click on the annotation and read the message. There won't be a thousand of them.

**Comment by haozturk** [comment]
Well actually the problem is that if there are multiple colors (as in the web app), they should have a meaning. Otherwise different colors give an impression as if they mean something. In this regard, I think Android app does not have a problem, but there should be only one color on the annotations of the web app. What do you think? @mstniy @abdullah-oncu-2015400237

**Comment by mstniy** [comment]
I agree

**Comment by abdullah-oncu-2015400237** [comment]
I think it is not required to make colorful. So we can use single color. I did it in order to try if I am able to do it or not.

**Comment by haozturk** [comment]
Okey then, @abdullah-oncu-2015400237 you can close this issue, once the multiple colors in the web annotations are reduced to a single color. Btw, I think we should the use the same color in Android and Web. Currently, annotation color is yellow in Android, so the web annotation color could be yellow, too.

**Comment by abdullah-oncu-2015400237** [comment]
I changed the annotation color to yellow
