### ISSUE TITLE
Internal error on backend result endpoint

### ISSUE THREAD

**Issue by abdullah-oncu-2015400237** [bounswe/bounswe2019group5#306]
postman api call:
`{
	"info": {
		"_postman_id": "6586f8d6-2ca2-462e-a58a-49a16621ddd9",
		"name": "toFurkan",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "http://35.158.176.194/message",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/json",
						"type": "text"
					},
					{
						"key": "Authorization",
						"value": "Token 821ed96cc5b655ef2aa7f7b9075622d4598be454",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"username\": \"enesoncu2\",\n\t\"text\": \"selam\"\n}"
				},
				"url": {
					"raw": "http://35.158.176.194/message",
					"protocol": "http",
					"host": [
						"35",
						"158",
						"176",
						"194"
					],
					"path": [
						"message"
					]
				}
			},
			"response": []
		}
	]
}`

**Comment by furkan-kadioglu** [comment]
postman api call is not result endpoint

**Comment by furkan-kadioglu** [comment]
Token is also invalid

**Comment by furkan-kadioglu** [comment]
I think that there is no bug but there is possible misuse of the admin panel, I have solved this problem by talking @abdullah-oncu-2015400237  and removin language table from the panel.
