### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2019group5#31]
Class diagram is improved.
New classes are added.

Attributes are updated

We need to discuss language and exercises at our weekly meeting.

**Comment by ymBila** [comment]
Started languages and exercises.

**Comment by ymBila** [comment]
Added report, user, exercise, request controllers. Modified exercises. Added to-do list to the diagram.
@Melteos @ymBila

**Comment by abdullah-oncu-2015400237** [comment]
We changed the classes (request controller, chat channel) we used in chat sequence diagram.

**Comment by Melteos** [comment]
We added UserInfo class and updated rating related classes. They are green now. @ymBila @Melteos

**Comment by Melteos** [comment]
Remaining topics to be added: 
- [ ] prof exam
- [ ] suggestion and acceptance of new materials
- [ ] credentials
After everything done, class fields and methods should be reviewed to control public/private identification.

**Comment by Melteos** [comment]
**updating with respect to feedback.**

1. - [ ] What is the “User” class, which is a subclass of “Registered User”? What does it represent within the system? (writing additional info to explain it better like user->basic user)

2. - [ ] The argument “Credentials” should be clarified. 

3. - [ ] Some of the information is duplicate within “UserInfo” and “Registered User” classes. @ymBila @Melteos (duplicate ones could be deleted from registered user, instead we can put a user object inside.)(Also rating and language relation is missing.)

4. - [ ] For example, there is a two-way relation between Admin and Report. Assuming that the two-way relation is correct, you need to add relevant fields to the classes such as adding the ID of the admin as a field to the Report class and adding the IDs of the reports as an array to the Admin class. (1 to many relation willl be deleted) @Melteos  @multiminparvo 

5. - [ ] In some relations, the multiplicity information is missing (many-to-one etc.) @all 
**(Everyone can update missing relation info as they see it)**

6. - [ ] Some methods are missing for example, in my opinion, there should be a method in Exercise Controller class such as addQuestion(Question question).(exerciseId missing, in controller there are methods without a parameter, ass addQuestions()) @furkan-kadioglu @mericturan 

7. - [ ] Also, I couldn’t see a method related to upload a new material or approving the updated materials?

8. - [ ] The Writing class should include an array of Annotation, as required by the composition relationship. @ymBila @slmttndrk @abdullahyldz 

9. - [ ] Proficiency exam.

**Comment by Melteos** [comment]
4. The relation between admin and report classes is deleted.

**Comment by slmttndrk** [comment]
7. New Material and Material Controller classes are added to the class diagram. And also, Admin class is rearranged according to these new classes.

**Comment by hasan-ozturk-2017400258** [comment]
2. I have created the "Credentials" class, specified its fields and connected with "Registered User" and "User Controller" class. Besides I have changed the direction of the connection of composition between "User Info" and "Registered User".

**Comment by slmttndrk** [comment]
I reviewed the "Credentials" class with its relationships and it is okey. And also, the direction of the connection between "User Info" and "Registered User" seems good now.
