### ISSUE TITLE
Android unit tests

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#312]
We don't have any tests now. This is not good practice. We need to make a habit of writing tests along with every new piece of functionality. We probably also need to add tests for existing functions.

**Comment by mstniy** [comment]
PR #326 adds some unit tests.
We should keep in mind to develop code and tests in parallel.

**Comment by ali-deser-2016400261** [comment]
PR https://github.com/bounswe/bounswe2019group5/pull/382 includes some units tests too.
