### ISSUE TITLE
Mock-Up & Scenario Improvements

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#32]
Scenario 1 will be enhanced (Shortening the sentences,)
Preconditions will be added
Scenario 3 Acceptance Criteria-Scenario conflict will be fixed

**Comment by ali-deser-2016400261** [comment]
Scenario 1 is also handled

**Comment by Melteos** [comment]
Scenario 3 hasn't been updated? @furkan-kadioglu @multiminparvo @muzunpostalci

**Comment by muzunpostalci** [comment]
Acceptance criteria for scenario 3 conflict is handled
I think all is done. I am closing this issue.
