### ISSUE TITLE
Sequence Diagram - Writing

### ISSUE THREAD

**Issue by ymBila** [bounswe/bounswe2019group5#33]
Creating a sequence diagram for writing use case.

**Comment by ymBila** [comment]
First version of writing sequence diagram is created. Needs review.

**Comment by Melteos** [comment]
**updating with respect to feedback.**

- [ ] In the 6th one, I think that creating a writing object at the first step, then sending a request to an expert and sending the essay is the correct flow of operations. 
(in sendWritingRequest method send a writing object as parameter.)

- [ ] Similar to the one above, I would like to give example from another diagram such as diagram 4. Before interacting with the Request Controller class, I think it would be better to create a Request object, which should be passed through the corresponding controller class.
(Request class will be added)

**Comment by ymBila** [comment]
Done, needs review.
