### ISSUE TITLE
Real time chat stop polling when exited

### ISSUE THREAD

**Issue by mstniy** [bounswe/bounswe2019group5#346]
We need to stop polling the chat history once the user leaves the screen.

**Comment by haozturk** [comment]
It seems like 5 seconds polling period is pretty much. When user sends a message, message appearance on the screen takes a bit long. I have tried it with 1 second and it was working fine. What do you think about this? Can we reduce it?

**Comment by mstniy** [comment]
1 or 2 should be fine

**Comment by haozturk** [comment]
Then, I am changing it from 5 to 2 and closing this issue. We can alter it later, if there occurs a problem.
