### ISSUE TITLE
Sequence Diagram - Chat

### ISSUE THREAD

**Issue by abdullahyldz** [bounswe/bounswe2019group5#36]
Chat sequence diagram is waiting for your revision.

**Comment by Melteos** [comment]
Bug: There is an extra timeline looking funny at User1.
And Mert and I thought that; it would be better if sendChatRequestToReceiver method goes to itself and there could be a request object returning to user 2 instead of sendChatRequestToReceiver going to user2 directly.

**Comment by abdullah-oncu-2015400237** [comment]
It would be better turning an object to user2 however I can not understand how can we turn something without user2 call some functoion?

**Comment by abdullah-oncu-2015400237** [comment]
Done.
