### ISSUE TITLE
final report 

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#375]
- [x] Final project assessment (Final Milestone -- assesses the whole process such as lessons learned)
- [x] Status of deliverables @haozturk 
- [x] A summary of coding work done by each team member (In tabular format)
- [x] Annotation implementation & W3C standard compliance
- [x] API documentation @furkan-kadioglu 
- [x] Requirements @furkan-kadioglu 
- [x] All design documents (diagrams, mockups etc.)
- [x] User manual 
- [x] System manual @furkan-kadioglu 
- [x] Project Plan (simplified version in a report-friendly format) @furkan-kadioglu

**Comment by furkan-kadioglu** [comment]
I have written my coding work.

**Comment by mstniy** [comment]
Me too

**Comment by Melteos** [comment]
I added;
1.2 frontend
2 frontend
7.design documents
my own coding work

**Comment by Melteos** [comment]
user manual added for web and android(android taken from the wiki page)

**Comment by ali-deser-2016400261** [comment]
I have written my individual report

**Comment by muzunpostalci** [comment]
I have written my summary of work

**Comment by ymBila** [comment]
I have written my coding work.
