### ISSUE TITLE
Research Interesting Repositories

### ISSUE THREAD

**Issue by slmttndrk** [bounswe/bounswe2019group5#4]
Explore GitHub repositories to discover repos that you like. Document them by
giving their references and describing what you liked.

Please add them to the [Research Page](https://github.com/bounswe/bounswe2019group5/wiki/Research-Page)

**Comment by furkan-kadioglu** [comment]
Done

**Comment by multiminparvo** [comment]
- If you interested in cryptocurrency, you should take a look.
https://github.com/DeviaVir/zenbot

- I like poetry and found this repo very interesting.It is a thesis project from Bilgi Uni. 
https://github.com/utkusen/romtu
https://utkusen.com/blog/turing-benzeri-bir-testi-gecen-ilk-makina-sairimiz-romtu.html

-Some brilliant guys created a program that you can commit your life events
https://github.com/ByronHsu/life-commit

I will attach more repo  to this comment later :)

**Comment by ymBila** [comment]
Done

**Comment by abdullahyldz** [comment]
done

**Comment by muzunpostalci** [comment]
Done

**Comment by hasan-ozturk-2017400258** [comment]
done

**Comment by slmttndrk** [comment]
Done

**Comment by ali-deser-2016400261** [comment]
Done

**Comment by Melteos** [comment]
done
