### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by ymBila** [bounswe/bounswe2019group5#40]
Create .gitignore file to stop commiting stuff like .DS_STORE files.

**Comment by abdullahyldz** [comment]
I added a .gitignore file  which only ignores MS_Store files for now. 
To add a file write its name to a new line with a 'dot' in front of it. 

[example .gitignore file](https://gist.github.com/octocat/9257657)
(I extracted it anyways)
# Compiled source #
###################
*.com
*.class
*.dll
*.exe
*.o
*.so

# Packages #
############
# it's better to unpack these files and commit the raw source
# git has its own built in compression methods
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip

# Logs and databases #
######################
*.log
*.sql
*.sqlite

# OS generated files #
######################
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
