### ISSUE TITLE
Last 5 sequence diagrams Review

### ISSUE THREAD

**Issue by abdullahyldz** [bounswe/bounswe2019group5#44]
Profile Search Diagram: 
Left-top tag name is 'searchinh' :)
Shouldn't registered user create CreateSearchingRequest with SearchType and SearchString. I think we can show them as function parameters. 

Other diagrams were already reviewed and corrected according to the feedbacks in previous issues. 

Nothing much to change. 
Great job!

**Comment by multiminparvo** [comment]
I discussed with other reviewer even if at the first look it is logical but we decide not to change the current search constructor.
