### ISSUE TITLE
Evaluation of the status of deliverables and its impact on your project plan

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#45]
We will write the statuses and summary of the progresses of our deliverables which are 1. Project repository with project documents and issue management
2. Requirements and mockups
3. Design documents.
We are working on this together with Hasan.

**Comment by Melteos** [comment]
We divided our work like this;
First five: @Melteos  Last five: @hasan-ozturk-2017400258 
1.Repository Research
2.Creation of Wiki-page
3.Project Requirements
4.User Scenarios
5.Mock ups
6.Label Philosophy https://github.com/bounswe/bounswe2019group5/wiki/Label-Philosophy
7.Communication Plan
8.Use Case Diagram
9.Class Diagram
10.Sequence Diagrams

**Comment by Melteos** [comment]
1.Liked Repositories(https://github.com/bounswe/bounswe2019group5/wiki/Research-Page): All of our members put at least one of their favorite repositories for our first assignment. This helped us get used to the issues and pages of the GitHub system and we began using GitHub efficiently doing our project.

2.Creation of Wiki(s)(https://github.com/bounswe/bounswe2019group5/wiki): Our wiki is the most important part of our project as it is. It contains all our work! Our home page and side-bar looks very neat and organized. Anyone can find any content related to our project easily.

3.Project Requirements(https://github.com/bounswe/bounswe2019group5/wiki/Project-Requirements): Having done many designs, and updating requirements accordingly, we are happy with our first version of the requirements. It is the core and beginning of our project. It's contents are clear and extensive. 

4.User Stories(https://github.com/bounswe/bounswe2019group5/wiki/User-Stories): The personas and stories we created are very well predicted and likely people that will use our platform. The descriptions are detailed enough and the motives are clear. They helped us imagine the user experience with our project.

5.Mockups(https://github.com/bounswe/bounswe2019group5/wiki/Mockups): The scenarios we picked were the things we weren't sure will look like, so completing them were clarifying. The way we divided our work was very efficient during this and we continued dividing our work efficiently after this assignment also. All three of our mockups look great.

**Comment by hasan-ozturk-2017400258** [comment]
1.Label Philosophy(https://github.com/bounswe/bounswe2019group5/wiki/Label-Philosophy): Labels helps us to understand the status, type, effort and priority of an issue. They are useful for identification of a specific issue among the others. 

2.Communication Plan(https://github.com/bounswe/bounswe2019group5/wiki/Communication-Plan): Communication is very critical for a team of 10 people. How to establish it is determined in communication plan in detail. It is created at the beginning of the semester with the consensus of every member of the team and the customer.

3.Use Case Diagram(https://github.com/bounswe/bounswe2019group5/wiki/Use-Case-Diagram): Use Case Diagram shows the relationship between users and functionalities of the program. The interaction of guest user, registered user and the admin user is shown in great detail in our use case diagram.

4.Class Diagram(https://github.com/bounswe/bounswe2019group5/wiki/Class-Diagram): Class diagram shows the classes and relationships between them. It is an high level abstraction of the project and it provides great benefits in the coding period. Our class diagram shows the classes, fields and the methods of the classes and connections between them in detail.

5.Sequence Diagrams(https://github.com/bounswe/bounswe2019group5/wiki/Sequence-Diagrams): Sequence Diagrams present key use cases of the classes. We have determined 10 key use cases and showed the action flow in the correct sequence diagram format. They describe the program flow well and they are easy understand.

**Comment by hasan-ozturk-2017400258** [comment]
> 1.Liked Repositories(https://github.com/bounswe/bounswe2019group5/wiki/Research-Page): All of our members put at least one of their favorite repositories for our first assignment. This helped us get used to the issues and pages of the GitHub system and we began using GitHub efficiently doing our project.
> 
> 2.Creation of Wiki(s)(https://github.com/bounswe/bounswe2019group5/wiki): Our wiki is the most important part of our project as it is. It contains all our work! Our home page and side-bar looks very neat and organized. Anyone can find any content related to our project easily.
> 
> 3.Project Requirements(https://github.com/bounswe/bounswe2019group5/wiki/Project-Requirements): Having done many designs, and updating requirements accordingly, we are happy with our first version of the requirements. It is the core and beginning of our project. It's contents are clear and extensive.
> 
> 4.User Stories(https://github.com/bounswe/bounswe2019group5/wiki/User-Stories): The personas and stories we created are very well predicted and likely people that will use our platform. The descriptions are detailed enough and the motives are clear. They helped us imagine the user experience with our project.
> 
> 5.Mockups(https://github.com/bounswe/bounswe2019group5/wiki/Mockups): The scenarios we picked were the things we weren't sure will look like, so completing them were clarifying. The way we divided our work was very efficient during this and we continued dividing our work efficiently after this assignment also. All three of our mockups look great.

Comment

**Comment by hasan-ozturk-2017400258** [comment]
> 1.Liked Repositories(https://github.com/bounswe/bounswe2019group5/wiki/Research-Page): All of our members put at least one of their favorite repositories for our first assignment. This helped us get used to the issues and pages of the GitHub system and we began using GitHub efficiently doing our project.
> 
> 2.Creation of Wiki(s)(https://github.com/bounswe/bounswe2019group5/wiki): Our wiki is the most important part of our project as it is. It contains all our work! Our home page and side-bar looks very neat and organized. Anyone can find any content related to our project easily.
> 
> 3.Project Requirements(https://github.com/bounswe/bounswe2019group5/wiki/Project-Requirements): Having done many designs, and updating requirements accordingly, we are happy with our first version of the requirements. It is the core and beginning of our project. It's contents are clear and extensive.
> 
> 4.User Stories(https://github.com/bounswe/bounswe2019group5/wiki/User-Stories): The personas and stories we created are very well predicted and likely people that will use our platform. The descriptions are detailed enough and the motives are clear. They helped us imagine the user experience with our project.
> 
> 5.Mockups(https://github.com/bounswe/bounswe2019group5/wiki/Mockups): The scenarios we picked were the things we weren't sure will look like, so completing them were clarifying. The way we divided our work was very efficient during this and we continued dividing our work efficiently after this assignment also. All three of our mockups look great.

Looks great!
Here is a little suggestion:
The sentence at the 2nd item could be updated as follows: "It contains all of our work so far."

**Comment by Melteos** [comment]
Thank you i updated it:)

**Comment by Melteos** [comment]
Yours also looks great! Just a minor correction: at 10. I guess it should be easy 'to' understand
