### ISSUE TITLE
Logo Design 

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#47]
Now, only team members can view this study.

**Comment by Melteos** [comment]
my suggestion: https://photos.google.com/share/AF1QipOuIo4Ri7_nxKMVruS28_2zjSAnfnSoYL98CmP8h0Zdlqwb4DHAQmH8xzivKSx-Ww?key=UUlZTVZxZms0LTYtNlU3cFNaU0ZGM3N6d2RJY1l3

**Comment by furkan-kadioglu** [comment]
I have added little color touches Meltem's suggestion. I think that it is nice but I need to svg format for more smooth logo. [Logo](https://github.com/bounswe/bounswe2019group5/blob/master/Images/logo.jpeg)
