### ISSUE TITLE
First 5 Sequence Diagrams Review

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#48]
**Related Link is here -> [I'm here 😅](https://github.com/bounswe/bounswe2019group5/wiki/Sequence-Diagrams)**

I have done reviewing the first five sequence diagrams. My comments are below.

- For the Sequence Diagram 1, I was the member of subgroup of constructing this one. After we got review from the customer, I have updated this one. Open for your other comments.
- Sequence Diagram 2 is constructed well. 
- Sequence Diagram 3 is also good, yet there is one point;
I think that the "Loop" part which consist of the main section of chatting should be under the Accept Chat and also Has Chat Channel sections.This construction might be violating the fact of chat is rejected by the other user. I.S.: Chatting Loop occurs even if the chat request is rejected.
As a solution : Loop Part can be defined abstractly and called inside both  Alt1.1 and Alt2.1 . Or a general if case can be defined.
- Sequence Diagram 4 is also nice. Just, I thought that should we keep the searching results in a different object and return this object to the user, or we return as an array like this? What does this array consist of? I'm waiting for others to comment
Sequence Diagram 5 is constructed in a same way of Sequence Diagram 4. Thus, same comment is valid for this one too.

**Comment by ali-deser-2016400261** [comment]
Sequence Diagram 2  :  
Sequence Diagram 2  :

**Comment by abdullah-oncu-2015400237** [comment]
About sequence diagram 3, we realized it before designing  but we thought that it is understandable and not need to do it. Should I change it really?

**Comment by ali-deser-2016400261** [comment]
If everyone agrees, it can stay like this.
We have contacted with the other group members and decided that they can stay as they were.
