### ISSUE TITLE
Agenda for next meeting(8)

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#50]
Aim: Creating our agenda for next meeting.
Everyone please comment here, what topics should we discuss in our meeting.

**Comment by Melteos** [comment]
Being careful whenever there is revision needed label on ones issue.

Being mindful about open issues, what's going on with them.

Closing finished issues.

Using the repo, wiki and side-bar efficiently.

**Comment by multiminparvo** [comment]
We need to discuss feedbacks about the executive summary and deliverable: https://github.com/bounswe/bounswe2019group5/issues/43

**Comment by multiminparvo** [comment]
Please don't hesitate to send  a message for your feedback
