### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#51]
[Project Planning Tool](https://www.projectlibre.com)

Meltem's deadline 05.04.2019 - 23.59
Review deadline 06.04.2019 - 23.59

Meltem will do project plan and then Furkan and Meriç will review.

**Comment by Melteos** [comment]
Unfortunately, I couldn't get projectlibre running on my computer properly.  So I wrote down the content of our project plan with details and passed it to Furkan. He accepted to put them on the projectlibre platform.

**Comment by Melteos** [comment]
Project plan will go [this page](https://github.com/bounswe/bounswe2019group5/wiki/Project-Plan)

**Comment by furkan-kadioglu** [comment]
I have written pod file but calendar is not accurate exactly due to ProjectLibre's problems. So Meltem is working on pod file.

**Comment by Melteos** [comment]
I have created the project plan [here](https://github.com/bounswe/bounswe2019group5/blob/master/projectplan352.pdf) .Due to my computer and my issues, the file is Turkish. Furkan(?) will convert it to English later.

**Comment by furkan-kadioglu** [comment]
I converted file to English but it has no check marks due to project libre's inconsistency. [engversion](https://github.com/bounswe/bounswe2019group5/blob/master/projectplan352.pdf)

**Comment by Melteos** [comment]
I have uploaded the updated file (with green ticks). Meric can do a review now.

**Comment by furkan-kadioglu** [comment]
I think that resource names which belongs to 7 and 9 flipped.

**Comment by Melteos** [comment]
> I think that resource names which belongs to 7 and 9 flipped.

Revision done. 👍 [updated](https://github.com/bounswe/bounswe2019group5/blob/master/projectplan352.pdf)
