### ISSUE TITLE
Project Plan 1.2

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#53]
Updating the existing project plan according to the feedback given.

I think some a diffrerent tool (not projectlibre) should be used this time, considering the problems we had earlier.
Modifications to be made:
-Indentation and bold text will be used to emphasize importance of some tasks.
-Some missing predecessors will be added.
-Milestone 2 will be added.

**Comment by Melteos** [comment]
I created new project plan using [SmartSheets](https://app.smartsheet.com)
I uploaded up to date project plan 1.2 [here](https://github.com/bounswe/bounswe2019group5/blob/master/projectplan352/Project%20Plan%201.2(Smartsheet)%20.pdf)
I assigned @furkan-kadioglu  to review it, because he and i did the first version of project plan together.

**Comment by furkan-kadioglu** [comment]
I think that it is less readable than previous plan but it is ok.
