### ISSUE TITLE
Agenda for next meeting

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#54]
Everyone should add topics that we should talk about in the next meeting.

**Comment by Melteos** [comment]
- Project plan revision, i opened the issue. Since we'll move to another platform (not ProjectLibre) someone else can takeover this issue.(This should be discussed)

- Determining the technologies we will be using at assignment 7.

- Discussing which APIs would be useful to our project: Language Learning Platform.

- Making a plan about how we will finish this assignment. Determining week by week goals.

**Comment by ymBila** [comment]
- Determining the work environment (IDE, etc.)
- Determining the coding conventions.
