### ISSUE TITLE
Get Data From Oxford Dictionary API

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2019group5#61]
We can fetch any data like definition, audio, word types etc from oxford dictionary.
As a guide we can use this link: https://developer.oxforddictionaries.com/documentation

If you need account info: You can reach from there: https://docs.google.com/spreadsheets/d/1TGgV7BR6upSFmqMY9ORjCJc1CXRo3wBGjPlHpBxA1iY/edit#gid=0

**Comment by multiminparvo** [comment]
There is a misalignment between github and me. Sorry for that.

Can you review it from this link please? https://github.com/bounswe/bounswe2019group5/commit/a186ab3ae1140e56b86dd8c0d1f7859f8894e3ba

**Comment by multiminparvo** [comment]
There is also some interesting issues about the Oxford Api.

1-) For some requests(like translate), an authentication error occurs. I couldnt find any solution for it
2-) And also, I cannot parse definition requests, I need to take whole data about a word. It is Ok but It would be better if I have only definitions for some cases

**Comment by slmttndrk** [comment]
The review is done. 
Authentication problem is solved. 
For simplicity, we prefer to take all data about a word.
