### ISSUE TITLE
Creation of Slack workspace and adding group members

### ISSUE THREAD

**Issue by furkan-kadioglu** [bounswe/bounswe2019group5#8]
Please share email which you want to use

**Comment by abdullah-oncu-2015400237** [comment]
abdullahenesoncu@gmail.com

**Comment by Melteos** [comment]
meltemsuicmez1@gmail.com
herkesin emaili vardır heralde personal pagelerimizde ordan da bulabilirsin

**Comment by ali-deser-2016400261** [comment]
Done.
