### ISSUE TITLE
Searching Travis and Informing the group 

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#82]
info will be provided.

**Comment by multiminparvo** [comment]
Travis has very good technical environment for test, deployment and intregration. 
We can run our code on Heroku if we want. It also supports aws environment. We just need to add script to our code and whole other things are handled by travis. It also notifies the coder for the unsuccessful  unit tests.

I am very aware of the other responsibilities we need to make it done. However, we can work on it after all urgent issues are finised 
https://docs.travis-ci.com/user/tutorial/
https://www.youtube.com/watch?v=Uft5KBimzyk
