### ISSUE TITLE
List and status of deliverables : Milestone 2

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#89]
Table format, just like milestone 1 report

**Comment by muzunpostalci** [comment]
I have created the template for status of deliverables. As we finish our task we can change "?" symbol with "✔" in our report.

**Comment by Melteos** [comment]
I changed the table to fit with the next part (3. Evaluation of the status of deliverables and its impact on your project plan. )
This is more like the way we did before and simpler. Hope you're okay with that 😅
