### ISSUE TITLE
Labels to reorganize

### ISSUE THREAD

**Issue by ali-deser-2016400261** [bounswe/bounswe2019group5#9]
As discussed in the lecture, we have decided to reorganize the labels and tags.

- [x] Furkan

- [x] Veli Can

**Comment by furkan-kadioglu** [comment]
I think effort labels can be useful for tracking.

**Comment by multiminparvo** [comment]
Yes, we need to also add the task type label and some label for workflow that i mentioned at this issue https://github.com/bounswe/bounswe2019group5/issues/15.

I think the most important part is writing a manifest about how should we use our labels.
