### ISSUE TITLE
Evaluation of tools and processes you have used to manage your team project : Milestone 2

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#92]
This is a lessons learned from the project development decisions made so far -- how
effectively are the tools are being utilized & what changes (if any) are needed as you
move forward?

**Comment by multiminparvo** [comment]
Slack,Node Js,Postman and Travis are added. If there is a problem with Travis integration. We might exclude it from our documentation @ymBila

**Comment by ymBila** [comment]
AWS, MySql and division of team into groups of 2 are evaluated.
