### ISSUE TITLE
API: Design of product (Wiki)	

### ISSUE THREAD

**Issue by Melteos** [bounswe/bounswe2019group5#93]
Creating Use Case, Class and Sequence diagrams of our practice-app.

**Comment by Melteos** [comment]
Use Case diagram is done, feedback is waited on Slack

**Comment by Melteos** [comment]
I added sequence diagrams

**Comment by abdullahyldz** [comment]
I added class diagram

**Comment by abdullahyldz** [comment]
Design diagrams are under bounswe2019group5/practice-app/design diagrams . 
Waiting for review

**Comment by abdullahyldz** [comment]
Assigned @slmttndrk as reviewer

**Comment by slmttndrk** [comment]
Designs are very attractive. It has lots of effort and creativity. Thanks for your interest.
